/**
 * playbookExport.ts — v7: exports a Playbook as .github/playbooks/{slug}.yml
 *
 * The YAML is documentary-only (not GHA-native). It preserves the full DAG
 * so it can be reimported later.
 */
import yaml from 'js-yaml';
import type { Playbook } from '@gha-dispatcher/shared';

/** Convert a playbook name to a safe filename slug. */
export function slug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/** Render a Playbook to a YAML string for .github/playbooks/{slug}.yml */
export function toGithubYaml(playbook: Playbook): string {
  const doc = {
    name: playbook.name,
    description: playbook.description ?? '',
    repo: playbook.repo_full,
    version: playbook.version,
    nodes: playbook.dag.nodes,
    edges: playbook.dag.edges,
  };

  const header = [
    '# generated by gha-dispatcher',
    `# playbook: ${playbook.name}`,
    `# repo: ${playbook.repo_full}`,
    `# exported: ${new Date().toISOString()}`,
    '',
  ].join('\n');

  return header + yaml.dump(doc, { lineWidth: 120, quotingType: '"' });
}

/** Return the canonical file path for a playbook. */
export function playbookFilePath(name: string): string {
  return `.github/playbooks/${slug(name)}.yml`;
}
